#production environment

#server:
#  port: 8788

spring:
#  profiles: prod
  datasource:
    url: jdbc:mysql://10.170.159.28:3306/nim_perftest?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: perf
    password: perftest
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


